services:

  php:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: php
    hostname: php
    volumes:
      - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./backend/:/var/www/php"
    working_dir: /var/www/php

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./backend/:/var/www/php:ro"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql_db

  mysql_db:
    image: mysql:9.3
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: qualix
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password2
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata: